import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";
import CartProvider from "./components/providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className="bg-slate-200 dark:bg-slate-950 flex flex-col items-center">
        <CartProvider
        mode="payment"
        cartMode="checkout-session"
        stripe="pk_test_51O1C8ZJq7Xqqclw9bcMEih0VUyRS3QamSLSKnWXu5rD5dKvWxJkcb8asY5DUbUhUERhulCuVo0Bj76s8VnsqPDzw00sbVrOSHR"
        currency="EUR"
      >
          <Header />
          {children}
          <Footer />
          </CartProvider>
        </body>
    </html>
  );
}
